- name: Install and configure K3s and ArgoCD
  hosts: all
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  vars_files:
    - vars.yaml
  roles:
    - common
    - k3s
    - argocd
