apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

images:
  - name: sprysio/simpleapi
    newName: sprysio/simpleapi
    newTag: main-0acf0a8bb3ecf45e1cc3efda52703502ecaea86c

secretGenerator:
  - name: simpleapi-secret
    literals:
      - POSTGRES_HOST=192.168.122.50
      - POSTGRES_DB=BrainRot
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=pass