apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

images:
  - name: sprysio/simpleapi
    newName: sprysio/simpleapi
    newTag: main-4a9c54e0f1a19d05d3933b97e0b997d90ab9fbe6

secretGenerator:
  - name: simpleapi-secret
    literals:
      - POSTGRES_HOST=192.168.122.50
      - POSTGRES_DB=BrainRot
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=pass