- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - gnupg
      - lsb-release
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - git
    state: present
