- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/get_k3s.sh
    mode: '0755'

- name: Install K3s
  ansible.builtin.shell: |
    /tmp/get_k3s.sh --write-kubeconfig-mode 644
  args:
    creates: /usr/local/bin/k3s
