apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apiserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sprysio/simpleAPIdevops.git'
    targetRevision: main
    path: apiserver/overlays/dev
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true