#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    
hostname: ubuntu

write_files:
  - path: /etc/netplan/01-netcfg.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens3:
            dhcp4: false
            addresses: [192.168.122.100/24]
            gateway4: 192.168.122.1
            nameservers:
              addresses: [8.8.8.8, 8.8.4.4]

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:
  - netplan generate
  - netplan apply
  - systemctl restart systemd-networkd
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart sshd