apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - statefulset.yaml
  - pvc.yaml
  - service.yaml
  
configMapGenerator:
  - name: postgres-init-db
    files:
      - 00init_script.sql