name: Make Docker Image

on:
  push:
    branches:
      - 'main'

env:
  VERSION: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 --tag  \
            ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} --push .

      - name: Modify Kustomize image tag
        run: |
            sed -i "s/newTag:.*/newTag: ${{ env.VERSION }}/" apiserver/overlays/dev/kustomization.yaml
    
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add apiserver/overlays/dev/kustomization.yaml          
          git commit -m "Update imageTag to ${{ env.VERSION }}"
          git push origin ${{ github.ref }}
    